/**
 * KGB Cup match play logic.
 *
 * Pure functions — no DB calls. Importable by API routes and client components.
 *
 * The match grid is generated by kgbCupMatchSchedule() (see ./schedule.ts) so
 * this module supports every group size in issue #107: 2v2 (5 matches w/
 * scramble in §3), 1v2/2v1 (4 matches over 2 nine-hole halves), 2v3/3v2 (9
 * matches with B-player double duty), and 3v3 (9 matches Latin square).
 *
 *   - Each section: count hole wins → section winner gets 1pt, tie = 0.5 each
 *   - First to majority wins (clinch = ceil(totalSections / 2))
 */

import {
  kgbCupMatchSchedule,
  type KgbPlayer,
  type KgbMatchSchedule,
  type KgbScheduledMatch,
  type KgbScheduledSection,
} from "./schedule.ts";

// ── Types ──

export interface PlayerHandicap {
  playerId: string;
  originalHandicap: number | null; // null = scratch (0)
  adjustedHandicap: number;
}

export interface PairHandicap {
  pairId: string;
  scrambleHandicap: number;
}

export interface HoleInfo {
  hole_number: number;
  par: number;
  handicap_index: number;
}

export interface HoleScore {
  foursome_id: string;
  hole_number: number;
  scorer_type: "player" | "pair";
  scorer_id: string;
  strokes: number;
}

export interface FoursomeData {
  id: string;
  pair_team1_id: string;
  pair_team2_id: string;
  team1_player_a_id: string | null;
  team1_player_b_id: string | null;
  team1_player_c_id: string | null;
  team2_player_a_id: string | null;
  team2_player_b_id: string | null;
  team2_player_c_id: string | null;
}

export interface MatchResult {
  matchIndex: number; // 0-4
  section: 1 | 2 | 3;
  label: string; // e.g. "Quack vs Spanky"
  team1ScorerName: string; // display name(s) for team1 scorer
  team2ScorerName: string; // display name(s) for team2 scorer
  team1ScorerId: string; // player_id or pair_id
  team2ScorerId: string;
  scorerType: "player" | "pair";
  holeResults: {
    hole: number;
    team1Net: number | null;
    team2Net: number | null;
    winner: "team1" | "team2" | "tie" | null; // null = not scored
  }[];
  team1Wins: number;
  team2Wins: number;
  ties: number;
  holesPlayed: number;
  sectionWinner: "team1" | "team2" | "halved" | "incomplete";
  team1Points: number;
  team2Points: number;
}

export interface FoursomeResult {
  foursomeId: string;
  matches: MatchResult[];
  team1TotalPoints: number;
  team2TotalPoints: number;
}

export interface OverallResult {
  team1Points: number;
  team2Points: number;
  totalSections: number;
  completedSections: number;
  winner: "team1" | "team2" | "tied" | "incomplete";
}

// ── Handicap Functions ──

/**
 * Compute adjusted handicaps: subtract the lowest handicap from all players.
 * Players with null handicap are treated as scratch (0).
 */
export function computeAdjustedHandicaps(
  players: { playerId: string; handicapIndex: number | null }[]
): PlayerHandicap[] {
  const withValues = players.map((p) => ({
    playerId: p.playerId,
    original: p.handicapIndex ?? 0,
  }));

  const lowest = Math.min(...withValues.map((p) => p.original));

  return withValues.map((p) => ({
    playerId: p.playerId,
    originalHandicap: players.find((pp) => pp.playerId === p.playerId)!.handicapIndex,
    adjustedHandicap: Math.round(p.original - lowest),
  }));
}

/**
 * Get the number of strokes a player receives on a specific hole.
 * Strokes go to hardest holes first (handicap_index 1 = hardest).
 */
export function getStrokesOnHole(
  adjustedHandicap: number,
  holeHandicapIndex: number,
  totalHoles: number = 18
): number {
  if (adjustedHandicap <= 0) return 0;

  const fullPasses = Math.floor(adjustedHandicap / totalHoles);
  const remainder = adjustedHandicap % totalHoles;

  // handicap_index 1 = hardest = gets strokes first
  // If holeHandicapIndex <= remainder, gets an extra stroke
  return fullPasses + (holeHandicapIndex <= remainder ? 1 : 0);
}

/**
 * Get strokes on a hole for a section (6-hole subset).
 * Re-ranks holes 1-6 by difficulty within the section.
 */
export function getStrokesOnHoleInSection(
  adjustedHandicap: number,
  holeNumber: number,
  sectionHoles: HoleInfo[]
): number {
  if (adjustedHandicap <= 0) return 0;

  // Rank holes within this section by handicap_index (ascending = hardest first)
  const ranked = [...sectionHoles].sort((a, b) => a.handicap_index - b.handicap_index);
  const rank = ranked.findIndex((h) => h.hole_number === holeNumber) + 1; // 1-based

  if (rank === 0) return 0;

  const sectionSize = sectionHoles.length;
  const fullPasses = Math.floor(adjustedHandicap / sectionSize);
  const remainder = adjustedHandicap % sectionSize;

  return fullPasses + (rank <= remainder ? 1 : 0);
}

/**
 * Get net score: gross minus strokes received.
 * Uses 18-hole distribution — strokes go to the hardest holes by course handicap index.
 */
export function getNetScore(
  gross: number,
  adjustedHandicap: number,
  holeHandicapIndex: number,
): number {
  const strokes = getStrokesOnHole(adjustedHandicap, holeHandicapIndex);
  return gross - strokes;
}

// ── Foursome Helpers ──

/**
 * Get section holes for a given section number. 2v2 uses three 6-hole
 * sections; 1v2 uses two 9-hole halves. Falls back to a hole-number range
 * filter so the section enum stays small (1 | 2 | 3).
 */
export function getSectionHoles(allHoles: HoleInfo[], section: 1 | 2 | 3, sectionHoleNumbers?: number[]): HoleInfo[] {
  if (sectionHoleNumbers && sectionHoleNumbers.length > 0) {
    const set = new Set(sectionHoleNumbers);
    return allHoles.filter((h) => set.has(h.hole_number));
  }
  switch (section) {
    case 1: return allHoles.filter((h) => h.hole_number >= 1 && h.hole_number <= 6);
    case 2: return allHoles.filter((h) => h.hole_number >= 7 && h.hole_number <= 12);
    case 3: return allHoles.filter((h) => h.hole_number >= 13 && h.hole_number <= 18);
  }
}

// ── Match Computation ──

/**
 * Compute match results for a foursome (or threesome / fivesome / sixsome).
 * Match grid is generated by kgbCupMatchSchedule(); supported group sizes:
 * 2v2 (5 matches w/ scramble), 1v2/2v1 (4 matches), 2v3/3v2 (9 matches),
 * 3v3 (9 matches). Returns an empty result when the group size is unsupported
 * or either side is empty.
 */
export function computeFoursomeResult(
  foursome: FoursomeData,
  scores: HoleScore[],
  playerHandicaps: Map<string, number>, // player_id -> adjusted handicap
  pairHandicaps: Map<string, number>,   // pair_id -> scramble handicap
  holes: HoleInfo[],
  playerNames?: Map<string, string>,    // player_id -> display_name
): FoursomeResult {
  const foursomeScores = scores.filter((s) => s.foursome_id === foursome.id);

  // Build score lookup: `${scorer_type}-${scorer_id}-${hole_number}` -> strokes
  const scoreLookup = new Map<string, number>();
  for (const s of foursomeScores) {
    scoreLookup.set(`${s.scorer_type}-${s.scorer_id}-${s.hole_number}`, s.strokes);
  }

  // Build team rosters in slot order (A, B, C). nulls dropped — the schedule
  // generator validates side sizes. Display name falls back to the empty
  // string when the lookup misses (a data-integrity issue, not a real
  // "missing player" — uneven sides are first-class).
  const toPlayer = (id: string | null): KgbPlayer | null => {
    if (!id) return null;
    return { id, displayName: playerNames?.get(id) || "" };
  };

  const team1Players: KgbPlayer[] = [
    toPlayer(foursome.team1_player_a_id),
    toPlayer(foursome.team1_player_b_id),
    toPlayer(foursome.team1_player_c_id),
  ].filter((p): p is KgbPlayer => p !== null);

  const team2Players: KgbPlayer[] = [
    toPlayer(foursome.team2_player_a_id),
    toPlayer(foursome.team2_player_b_id),
    toPlayer(foursome.team2_player_c_id),
  ].filter((p): p is KgbPlayer => p !== null);

  if (team1Players.length === 0 || team2Players.length === 0) {
    return { foursomeId: foursome.id, matches: [], team1TotalPoints: 0, team2TotalPoints: 0 };
  }

  let schedule: KgbMatchSchedule;
  try {
    schedule = kgbCupMatchSchedule(team1Players, team2Players);
  } catch {
    // Unsupported group size (1v1, 1v3, 4v4, etc.) — admin will see no matches.
    return { foursomeId: foursome.id, matches: [], team1TotalPoints: 0, team2TotalPoints: 0 };
  }

  // Flatten the schedule into MatchResults. Same per-hole logic as before;
  // only the match list shape differs across group sizes.
  const matches: MatchResult[] = schedule.sections.flatMap((sec) => {
    const sectionHoles = getSectionHoles(holes, sec.section, sec.holes);
    return sec.matches.map((m) => buildMatchResult(m, sec, sectionHoles, foursome, team1Players, team2Players, scoreLookup, playerHandicaps, pairHandicaps));
  });

  return {
    foursomeId: foursome.id,
    matches,
    team1TotalPoints: matches.reduce((sum, m) => sum + m.team1Points, 0),
    team2TotalPoints: matches.reduce((sum, m) => sum + m.team2Points, 0),
  };
}

/**
 * Build a single MatchResult from a scheduled match. For scramble sections
 * the scorer is the pair (uses pair_team1_id / pair_team2_id and
 * pairHandicaps); otherwise it's the individual players from the schedule.
 *
 * The B-player double-duty rule for 2v3 falls out for free: the schedule
 * emits the same player.id in two matches per section, the score lookup
 * keys by (scorer_type, scorer_id, hole), and both matches read the same
 * gross score. One ball, two matches.
 */
function buildMatchResult(
  m: KgbScheduledMatch,
  sec: KgbScheduledSection,
  sectionHoles: HoleInfo[],
  foursome: FoursomeData,
  team1Players: KgbPlayer[],
  team2Players: KgbPlayer[],
  scoreLookup: Map<string, number>,
  playerHandicaps: Map<string, number>,
  pairHandicaps: Map<string, number>,
): MatchResult {
  const isScramble = sec.format === "scramble";
  const scorerType: "player" | "pair" = isScramble ? "pair" : "player";

  const team1ScorerId = isScramble ? foursome.pair_team1_id : m.team1Player.id;
  const team2ScorerId = isScramble ? foursome.pair_team2_id : m.team2Player.id;
  const team1ScorerName = isScramble ? team1Players.map((p) => p.displayName).join(" & ") : m.team1Player.displayName;
  const team2ScorerName = isScramble ? team2Players.map((p) => p.displayName).join(" & ") : m.team2Player.displayName;

  const t1Handicap = isScramble
    ? (pairHandicaps.get(foursome.pair_team1_id) || 0)
    : (playerHandicaps.get(m.team1Player.id) || 0);
  const t2Handicap = isScramble
    ? (pairHandicaps.get(foursome.pair_team2_id) || 0)
    : (playerHandicaps.get(m.team2Player.id) || 0);

  const holeResults = sectionHoles
    .slice()
    .sort((a, b) => a.hole_number - b.hole_number)
    .map((hole) => {
      const t1Gross = scoreLookup.get(`${scorerType}-${team1ScorerId}-${hole.hole_number}`);
      const t2Gross = scoreLookup.get(`${scorerType}-${team2ScorerId}-${hole.hole_number}`);

      if (t1Gross === undefined || t2Gross === undefined) {
        return {
          hole: hole.hole_number,
          team1Net: t1Gross !== undefined ? getNetScore(t1Gross, t1Handicap, hole.handicap_index) : null,
          team2Net: t2Gross !== undefined ? getNetScore(t2Gross, t2Handicap, hole.handicap_index) : null,
          winner: null as "team1" | "team2" | "tie" | null,
        };
      }

      const t1Net = getNetScore(t1Gross, t1Handicap, hole.handicap_index);
      const t2Net = getNetScore(t2Gross, t2Handicap, hole.handicap_index);
      let winner: "team1" | "team2" | "tie";
      if (t1Net < t2Net) winner = "team1";
      else if (t2Net < t1Net) winner = "team2";
      else winner = "tie";
      return { hole: hole.hole_number, team1Net: t1Net, team2Net: t2Net, winner };
    });

  const scoredHoles = holeResults.filter((h) => h.winner !== null);
  const team1Wins = scoredHoles.filter((h) => h.winner === "team1").length;
  const team2Wins = scoredHoles.filter((h) => h.winner === "team2").length;
  const ties = scoredHoles.filter((h) => h.winner === "tie").length;
  const holesPlayed = scoredHoles.length;

  // Section complete when every hole in the section has been scored.
  const isComplete = holesPlayed === sectionHoles.length;

  let sectionWinner: "team1" | "team2" | "halved" | "incomplete";
  let team1Points = 0;
  let team2Points = 0;
  if (!isComplete) {
    sectionWinner = "incomplete";
  } else if (team1Wins > team2Wins) {
    sectionWinner = "team1";
    team1Points = 1;
  } else if (team2Wins > team1Wins) {
    sectionWinner = "team2";
    team2Points = 1;
  } else {
    sectionWinner = "halved";
    team1Points = 0.5;
    team2Points = 0.5;
  }

  return {
    matchIndex: m.matchIndex,
    section: sec.section,
    label: m.label,
    team1ScorerName,
    team2ScorerName,
    team1ScorerId,
    team2ScorerId,
    scorerType,
    holeResults,
    team1Wins,
    team2Wins,
    ties,
    holesPlayed,
    sectionWinner,
    team1Points,
    team2Points,
  };
}

/**
 * Compute overall results across all foursomes.
 */
export function computeOverallResults(
  foursomeResults: FoursomeResult[]
): OverallResult {
  let team1Points = 0;
  let team2Points = 0;
  let totalSections = 0;
  let completedSections = 0;

  for (const fr of foursomeResults) {
    for (const m of fr.matches) {
      totalSections++;
      if (m.sectionWinner !== "incomplete") {
        completedSections++;
        team1Points += m.team1Points;
        team2Points += m.team2Points;
      }
    }
  }

  const clinch = Math.ceil(totalSections / 2);
  let winner: "team1" | "team2" | "tied" | "incomplete";
  if (team1Points >= clinch) winner = "team1";
  else if (team2Points >= clinch) winner = "team2";
  else if (completedSections === totalSections && totalSections > 0) {
    if (team1Points > team2Points) winner = "team1";
    else if (team2Points > team1Points) winner = "team2";
    else winner = "tied";
  } else {
    winner = "incomplete";
  }

  return { team1Points, team2Points, totalSections, completedSections, winner };
}

/**
 * Format match status as a human-readable string.
 * e.g. "2 UP thru 4", "All Square thru 6", "HALVED"
 */
export function formatMatchStatus(match: MatchResult): string {
  const t1Name = match.team1ScorerName;
  const t2Name = match.team2ScorerName;

  if (match.sectionWinner === "incomplete") {
    if (match.holesPlayed === 0) return "Not started";
    const lead = Math.abs(match.team1Wins - match.team2Wins);
    if (lead === 0) return `All Square thru ${match.holesPlayed}`;
    const leader = match.team1Wins > match.team2Wins ? t1Name : t2Name;
    const totalHoles = match.holeResults.length;
    const remaining = totalHoles - match.holesPlayed;
    if (remaining > 0 && lead === remaining) {
      return `${leader} Dormie (${lead} UP, ${remaining} to play)`;
    }
    return `${leader} ${lead} UP thru ${match.holesPlayed}`;
  }

  if (match.sectionWinner === "halved") return "HALVED";
  const lead = Math.abs(match.team1Wins - match.team2Wins);
  const leader = match.sectionWinner === "team1" ? t1Name : t2Name;
  return `${leader} wins ${lead} UP`;
}
